### ISSUE TITLE
xa_isPopEnable属性使用咨询

### ISSUE THREAD

**Issue by fenghonghui89** [XangAm/XANavBarTransition#3]
你好，请问xa_isPopEnable可以在viewDidAppear调用吗？
有这么一个场景，某页面默认是xa_isPopEnable=yes，但点击页面上某个按钮，弹出一个半透明黑色弹窗，此时xa_isPopEnable设置为NO，然后点击关闭按钮关闭黑色弹窗后恢复为YES。
我试过无效，请问有好的解决方案不？我的想法是黑色弹窗出现的时候防止用户滑动退出页面。
谢谢。

**Comment by aboutlan** [comment]
你好 @fenghonghui89 ，xa_isPopEnable 属性是可以在 viewDidAppear 进行调用的。
但是 xa_isPopEnable 属性在框架里面是作为转场行为的一个要素，所以初始化的时候就决定了它的行为，当前不能通过修改数值来改变其行为。你可以尝试使用 xa_isTransitionEnable 属性。 感谢回馈～
